module.exports = {
  'rules': {
    'color-no-invalid-hex' : true,
    'function-comma-newline-after' : 'never-multi-line',
    'function-comma-newline-after' : 'never-multi-line',
    'function-comma-space-after' : 'always',
    'function-comma-space-before' : 'never',
    'function-linear-gradient-no-nonstandard-direction' : true,
    'function-name-case' : 'lower',
    'function-url-quotes' : 'always',
    'function-whitespace-after' : 'always',
    'string-quotes' : 'single',
    'string-no-newline' : true,
    'length-zero-no-unit' : true,
    'unit-case' : 'lower',
    'unit-no-unknown' : true,
    'value-keyword-case' : 'lower',
    'value-no-vendor-prefix' : true,
    'value-list-max-empty-lines' : 0,
    'property-case' : 'lower',
    'property-no-unknown' : true,
    'property-no-vendor-prefix' : true,
    'keyframe-declaration-no-important' : true,
    'declaration-bang-space-after' : 'never',
    'declaration-bang-space-before' : 'always',
    'declaration-colon-space-after' : 'always',
    'declaration-colon-space-before' : 'never',
    'declaration-empty-line-before' : 'never',
    'declaration-block-no-duplicate-properties' : true,
    'declaration-block-no-shorthand-property-overrides' : true,
    'declaration-block-semicolon-newline-after' : 'always',
    'declaration-block-semicolon-space-before' : 'never',
    'declaration-block-single-line-max-declarations' : 1,
    'declaration-block-trailing-semicolon' : 'always',
    'selector-attribute-brackets-space-inside' : 'never',
    'selector-attribute-operator-space-after' : 'never',
    'selector-attribute-operator-space-before' : 'never',
    'media-feature-parentheses-space-inside' : 'never',
    'media-query-list-comma-space-before' : 'never',
    'media-feature-colon-space-before' : 'never',
    'selector-pseudo-class-parentheses-space-inside' : 'never',
    'selector-attribute-quotes' : 'always',
    'selector-combinator-space-after' : 'always',
    'selector-combinator-space-before' : 'always',
    'selector-list-comma-newline-after' : 'always',
    'rule-empty-line-before' : [
      'always',
      {
        except: [
          'after-single-line-comment'
        ]
      }
    ],
    'media-feature-colon-space-after' : 'always',
    'at-rule-semicolon-newline-after' : 'always',
    'media-query-list-comma-space-after' : 'always',
    'selector-descendant-combinator-no-non-space' : true,
    'selector-max-compound-selectors' : 3,
    'selector-no-id' : true,
    'no-duplicate-selectors' : true,
    'no-extra-semicolons' : true,
    'no-unknown-animations' : true,
    'selector-pseudo-class-no-unknown' : true,
    'selector-pseudo-element-no-unknown' : true,
    'selector-type-no-unknown' : true,
    'media-feature-name-no-unknown' : true,
    'media-feature-name-no-vendor-prefix' : true,
    'at-rule-no-unknown' : [
      true,
      {
        ignoreAtRules: [
          'mixin',
          'if',
          'content',
          'else',
          'include',
          'extend',
          'function',
          'each',
          'return',
          'error',
          'warn',
          'for'
        ]
      }
    ],
    'at-rule-no-vendor-prefix' : true,
    'comment-no-empty' : true,
    'selector-max-empty-lines' : 0,
    'max-empty-lines' : 1,
    'max-nesting-depth' : 3,
    'selector-pseudo-class-case' : 'lower',
    'selector-pseudo-element-case' : 'lower',
    'at-rule-name-case' : 'lower',
    'selector-type-case' : 'lower',
    'media-feature-name-case' : 'lower',
    'selector-pseudo-element-colon-notation' : 'double',
    'font-family-no-duplicate-names' : true
  }
}
